### PR TITLE
KNOX-2779 - support multiple hosts for gateway.host config

### PR DESCRIPTION
**Pull request by nanhuirong**
support multiple hosts for gateway.host config

### CODE REVIEW

**Review by lmccay — CHANGES_REQUESTED** [review]
@nanhuirong - we need to get unit tests to insure that previous behavior with only one in the list and new behavior with multiples work as expected and do not regress in the future.

**Comment by nanhuirong** [comment]
> @nanhuirong - we need to get unit tests to insure that previous behavior with only one in the list and new behavior with multiples work as expected and do not regress in the future.

@lmccay -  We need two network cards for this config and can't assume another ip. Thus, I just test the gateway.host properties.

**Comment by nanhuirong** [comment]
@smolnar82 , Please review the code.

**Comment by lmccay** [comment]
@nanhuirong - thank you for your pull request. I've merged this into master and it will be included in the next release.
Let's also file a JIRA for documentation for this improvement.

**Comment by nanhuirong** [comment]
> Let's also file a JIRA for documentation for this improvement.

I don't know how to do for this. Do you have any suggestion?

**Comment by lmccay** [comment]
@nanhuirong - sure - start by filing a JIRA and describe what documentation needs to be updated and then you can provide the documentation in the JIRA or follow the process description in https://cwiki.apache.org/confluence/display/KNOX/Contribution+Process#ContributionProcess-DocumentationContributorWorkflow

Note that the site docs are in subversion, not in github.
So, you will likely have to attach the patch file to the JIRA.

Thanks for your interest and followup!

**Pull request merged**
