### PR TITLE
KNOX-2717: upgrade shiro

### PR DESCRIPTION
**Pull request by pjfanning**
(It is very **important** that you created an Apache Knox JIRA for this change and that the PR title/commit message includes the Apache Knox JIRA ID!)

## What changes were proposed in this pull request?

https://issues.apache.org/jira/browse/KNOX-2717

security issue in shiro

## How was this patch tested?

(Please explain how this patch was tested. For instance: running automated unit/integration tests, manual tests. Please write down your test steps as detailed as possible)
(If this patch involves UI changes, please attach a screen-shot; otherwise, remove this)

Please review [Knox Contributing Process](https://cwiki.apache.org/confluence/display/KNOX/Contribution+Process#ContributionProcess-GithubWorkflow) before opening a pull request.

### CODE REVIEW

**Comment by smolnar82** [comment]
My 2 cents:
- this change contains 2 upgrades in fact:
  - shiro
  - log4j2
  Please make them committed separately.
- I'd love to see some details on the tests you were executing

**Comment by pjfanning** [comment]
@smolnar82 I reverted the log4j change - I added it because the CI didn't kick off for my initial commit. I'm relying on the CI build test the changes. I'm not a Knox user. I'm involved with the ASF Security team and am trying to get ASF projects to start looking at their transitive dependencies. The ASF get many requests from users and now even government agencies asking us why we don't have all the latest security fixes applied in our projects.

**Comment by smolnar82** [comment]
@pjfanning - I got it.
In this case, please give me some time to checkout this PR and execute some sanity checks (at least PAM/LDAP authentication on the Shiro side).

**Comment by smolnar82** [comment]
Verified basic authentication methods. Let's wait for a green TravisCI run and merge this one.

**Pull request merged**
