### PR TITLE
New Knox Gateway Service for ElasticSearch

### PR DESCRIPTION
**Pull request by dequanchen**
The service has been tested to work for the following scenarios:
(1)	No-LDAP, Local-LDAP or company-specific-LDAP authentication in the Knox gateway;
(2)	Any Elasitcsearch Index - creation, deletion, refresshing and data - writing, updating and retrieval;
(3)	Elasticsearch node root query.

### CODE REVIEW

**Comment by dequanchen** [comment]
New ElasticSearch Knox Gateway Service

**Comment by moresandeep** [comment]
Hello @dequanchen 
Thanks for the ElasticSearch service ! 
Can you open a [JIRA](https://issues.apache.org/jira/projects/KNOX) for Knox and provide a patch, we are not yet accepting PRs for Knox :(

**Comment by dequanchen** [comment]
Hello Sandeep,

Thanks for your email. I have just created the JIRA with a patch containing
the two critical files for the ElasticSearch service.

Merry Christmas!

Have a great day!


Best wishes,



Dequan



*Dequan Chen, Ph.D*


*LinkedIn*: *https://www.linkedin.com/in/dequan-chen-5b0a37bb/
<https://www.linkedin.com/in/dequan-chen-5b0a37bb/>*


*DataWorks  Summit / Hadoop Summit 2017 Speaker:
**https://dataworkssummit.com/san-jose-2017/sessions/securing-enterprise-healthcare-big-data-by-the-combination-of-knoxf5-ranger-tfa-and-kerberos-coupled-with-enterprise-active-directory-and-ldap
<https://dataworkssummit.com/san-jose-2017/sessions/securing-enterprise-healthcare-big-data-by-the-combination-of-knoxf5-ranger-tfa-and-kerberos-coupled-with-enterprise-active-directory-and-ldap>*/
 ==  Slides
<https://www.slideshare.net/Hadoop_Summit/securing-enterprise-healthcare-big-data-by-the-combination-of-knoxf5-ranger-tfa-and-kerberos-coupled-with-enterprise-active-directory-and-ldap>

*On Hortonworks Web or YouTube:  * http://hortonworks.com/customers/ |
http://hortonworks.com/customer/mayo-clinic/  or
*https://www.youtube.com/watch?v=w3T83zV-J7A&feature=youtu.be
<https://www.youtube.com/watch?v=w3T83zV-J7A&feature=youtu.be>*



*Home* | (507) 208-1599 (C) |dequanchen2007@gmail.com
<chen.dequan@mayo.edu> (P)
| 1917 Century Hills Drive NE | Rochester, MN 55906


*Mayo Clinic *(www.mayoclinic.org
<https://mail.google.com/_/mail-static/_/js/main/m_i,t/rt=h/ver=am293eyFlXI.en./sv=1/am=!v8Czf-oeNMn1BO3a1PgLQrBoxwvTnkWnVEs3SWgFkVSnMtacHPKN7pbwINtZpbZbUD24Nw/www.mayoclinic.org>
) |Big Data Core Team, Data Resource Management, IT | 507-293-8489|
chen.dequan@mayo.edu | 200 First Street SW | Rochester, MN 55905

**Comment by dequanchen** [comment]
The patch KNOX-1155-001.patch was created in the JIRA -https://issues.apache.org/jira/browse/KNOX-1155. So I am hereby close the PR. Dequan 4/27/2015

**Comment by dequanchen** [comment]
Sandeep,

Thanks for your comment. I have closed the PR and the patch was attached
long time ago in the JIRA Knox-1155 as follows:
The patch KNOX-1155-001.patch --- in the JIRA:
https://issues.apache.org/jira/browse/KNOX-1155.

In addition, where to submit the documentation for testing - I created at
the beginning of 2018. But I didn't get the instructions from you or others
so I did not submit it to the community yet.

Dequan
4/27/2018

Have a great day!


Best wishes,



Dequan

**Pull request closed without merging**
