### PR TITLE
KNOX-2898 - Reconsider the usage of sso.unauthenticated.path.list

### PR DESCRIPTION
**Pull request by zeroflag**
## What changes were proposed in this pull request?

Unauthenticated path list doesn't work when hadoop-jwt cookie exists but it's invalid / expired.

## How was this patch tested?

```xml
<topology>
   <gateway>
      <provider>
         <role>federation</role>
         <name>SSOCookieProvider</name>
         <enabled>true</enabled>
         <param>
              <name>sso.unauthenticated.path.list</name>
              <value>/favicon.ico;test;unsafepath</value>
         </param>
      </provider>
      <provider>
            <role>identity-assertion</role>
            <name>Default</name>
            <enabled>true</enabled>
      </provider>

        <provider>
            <role>hostmap</role>
            <name>static</name>
            <enabled>true</enabled>
            <param>
                <name>localhost</name>
                <value>sandbox,sandbox.hortonworks.com</value>
            </param>
        </provider>
    </gateway>
    <service>
        <role>CM-UI</role>
        <url>https://www.google.com</url>
    </service>
</topology>
```

```bash
 curl --cookie "hadoop-jwt=invalid" -k https://localhost:8443/gateway/sandbox/favicon.ico
```

### CODE REVIEW

**Review by moresandeep — COMMENTED** [review]
The concern I have is that one can add any path to that list and bypass authentication. Feature or Bug? :)

**Comment by zeroflag** [comment]
@moresandeep 
If you omit the `hadoop-jwt` completely you can still bypass the authentication, I thought that was the goal to bypass the autnetication. However if your token expires you'll be redirected to the login page when accessing an unauthenticated path, such as /favicon.

In other filters such as `HadoopAuthFilter` we check the unauthenticated path first and do an early return if the path is there.

**Review by smolnar82 — APPROVED** [review]
LGTM.
@moresandeep - Have you had the time to think about @zeroflag 's previous comment?

**Review by moresandeep — APPROVED** [review]
Thanks @zeroflag! looks good!

**Comment by moresandeep** [comment]
> @moresandeep If you omit the `hadoop-jwt` completely you can still bypass the authentication, I thought that was the goal to bypass the autnetication. However if your token expires you'll be redirected to the login page when accessing an unauthenticated path, such as /favicon.
> 
> In other filters such as `HadoopAuthFilter` we check the unauthenticated path first and do an early return if the path is there.

I see, that makes sense. Thanks !

**Pull request merged**
