### PR TITLE
KNOX-2339 - Add Github Actions for CI

### PR DESCRIPTION
**Pull request by risdenk**
## What changes were proposed in this pull request?

Add Github Actions for CI

## How was this patch tested?

It ran on my fork: https://github.com/risdenk/knox/actions/runs/75532177

### CODE REVIEW

**Comment by risdenk** [comment]
Ah ha it does run on my fork branch: https://github.com/risdenk/knox/runs/577938164

**Comment by risdenk** [comment]
This is blocked by #312 and failed due to java-support issues which has been reverted. I'll rebase once #312 is in.

**Comment by smolnar82** [comment]
In Travis, we have `shellcheck` support too. There is a `shellcheck` action in GitHub Actions too:
https://github.com/marketplace/actions/shellcheck

Is it possible that you integrate it?

**Comment by risdenk** [comment]
Yea I was just trying to get a start on this. I had added shellcheck but it was causing issues. I will go back and look into it.

**Pull request merged**
