### PR TITLE
KNOX-2475: url creation failure caused by spaces in url

### PR DESCRIPTION
**Pull request by newHE3DBer**
(It is very **important** that you created an Apache Knox JIRA for this change and that the PR title/commit message includes the Apache Knox JIRA ID!)

## What changes were proposed in this pull request?
https://issues.apache.org/jira/browse/KNOX-2475
solve url creation failure caused by spaces in url

## How was this patch tested?
running automated unit/integration tests, manual tests.
step1. cd  knox/gateway-spi/
step2. mvn test

Please review [Knox Contributing Process](https://cwiki.apache.org/confluence/display/KNOX/Contribution+Process#ContributionProcess-GithubWorkflow) before opening a pull request.

### CODE REVIEW

**Comment by smallstudent666** [comment]
image

Is the build failure due to environmental issues？

**Comment by smallstudent666** [comment]
@risdenk

**Comment by newHE3DBer** [comment]
@lmccay

**Comment by newHE3DBer** [comment]
@moresandeep

**Review by moresandeep — CHANGES_REQUESTED** [review]
@newHE3DBer thank you! thanks for catching and providing a patch. Can you add a positive unit test to test this code change. 
Basically, just add a new test case in [ConfigurableDispatchTest.testGetDispatchUrl() ](https://github.com/apache/knox/blob/81591369501b82880987d09e5704d685d97aaf4a/gateway-spi/src/test/java/org/apache/knox/gateway/dispatch/ConfigurableDispatchTest.java#L49)
and we should be all set.

**Comment by newHE3DBer** [comment]
@moresandeep  I am already submitting to https://github.com/apache/knox/pull/408

**Comment by moresandeep** [comment]
This is abandoned

**Pull request closed without merging**
