### PR TITLE
KNOX-2337 - Upgrade pac4j to 4.0.3 and opensaml to 3.4.5

### PR DESCRIPTION
**Pull request by risdenk**
## What changes were proposed in this pull request?

* Upgrade pac4j to 4.0.3
* Upgrade opensaml to 3.4.5

## How was this patch tested?

* `mvn -U -T.75C clean verify -Ppackage,release -Dshellcheck`

### CODE REVIEW

**Comment by risdenk** [comment]
Need to fix a few more dependencies for this to work:

```
Dependency convergence error for org.glassfish.jaxb:jaxb-runtime:2.3.2 paths to dependency are:
+-org.apache.knox:gateway-provider-security-pac4j:1.4.0-SNAPSHOT
  +-org.apache.knox:gateway-server:1.4.0-SNAPSHOT
    +-com.sun.xml.ws:jaxws-ri:2.3.2
      +-com.sun.xml.ws:jaxws-rt:2.3.2
        +-org.glassfish.jaxb:jaxb-runtime:2.3.2
and
+-org.apache.knox:gateway-provider-security-pac4j:1.4.0-SNAPSHOT
  +-org.pac4j:pac4j-saml:4.0.0
    +-org.opensaml:opensaml-storage-impl:4.0.0
      +-org.hibernate:hibernate-core:5.4.12.Final
        +-org.glassfish.jaxb:jaxb-runtime:2.3.1

[WARNING] 
Dependency convergence error for com.sun.mail:javax.mail:1.6.1 paths to dependency are:
+-org.apache.knox:gateway-provider-security-pac4j:1.4.0-SNAPSHOT
  +-org.pac4j:pac4j-oidc:4.0.0
    +-com.nimbusds:oauth2-oidc-sdk:7.3
      +-com.sun.mail:javax.mail:1.6.1
and
+-org.apache.knox:gateway-provider-security-pac4j:1.4.0-SNAPSHOT
  +-org.pac4j:pac4j-oidc:4.0.0
    +-com.sun.mail:javax.mail:1.6.2
```

**Comment by risdenk** [comment]
Rebased to get new github actions check as well (expected to fail with same error)

**Comment by leleuj** [comment]
Be careful: `pac4j-opensaml` v4.0.0 is based on OpenSAML v4 which requires the JDK 11. Use `pac4j-saml-opensamlv3` to stay on OpenSAML v3 and JDK 8.

**Comment by risdenk** [comment]
Thanks @leleuj! I'll update accordingly.

**Pull request merged**
