### PR TITLE
KNOX-1760 - Created Pull Request template

### PR DESCRIPTION
**Pull request by smolnar82**
## What changes were proposed in this pull request?

Created the PR template for Knox

## How was this patch tested?

I edited this template using a Markdown editor and copy pasted the submitted template here to ensure it looks like as expected.

### CODE REVIEW

**Comment by smolnar82** [comment]
@risdenk please review; thanks!

**Comment by smolnar82** [comment]
@risdenk if you are OK with my changes could you please use the `Squash and merge` action to merge this PR?

**Comment by risdenk** [comment]
Thanks for putting this together @smolnar82 - Would be good to have a line in there about making sure there is an Apache Knox JIRA for this change and that the PR title/commit message includes the Apache Knox JIRA.

**Comment by smolnar82** [comment]
Thanks for the review @risdenk! I'll submit the new patch in 5 mins.

**Comment by risdenk** [comment]
@smolnar82 used squash and merge for this.

**Pull request merged**
