### PR TITLE
KNOX-2772 - add configuration for jetty renegotiation

### PR DESCRIPTION
**Pull request by nanhuirong**
disable renegotiation for embedded jetty

### CODE REVIEW

**Review by lmccay — CHANGES_REQUESTED** [review]
See my comment requesting a unit test.
Otherwise, LGTM.

**Review by smolnar82 — CHANGES_REQUESTED** [review]
Please address my review comments as well as add a unit test s @lmccay requested. Thanks!

**Comment by smolnar82** [comment]
Thanks for the new patchset, @nanhuirong !
I've just checked [Jetty's API](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/util/ssl/SslContextFactory.html#isRenegotiationAllowed()) and found that the default value is `true`:
```
[@ManagedAttribute](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/util/annotation/ManagedAttribute.html)("Whether renegotiation is allowed") public boolean isRenegotiationAllowed()
Returns:
whether TLS renegotiation is allowed (true by default)
```
Hence the question: why do we want to change the default to `false`?

Cc. @lmccay

**Comment by nanhuirong** [comment]
> https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/util/annotation/ManagedAttribute.html)("Whether renegotiation is allowed"

In our scenario，we should provide better security for the gateway. After all, the IP maybe a public IP.

**Comment by smolnar82** [comment]
> > [https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/util/annotation/ManagedAttribute.html)("Whether](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/util/annotation/ManagedAttribute.html)(%22Whether) renegotiation is allowed"
> 
> In our scenario，we should provide better security for the gateway. After all, the IP maybe a public IP.

What prevents you to set this new config to `false` in your environment and leave the default as `true` as intended by Jetty developers? They also introduced a limit (defaults to 5) that would fix the original CVE of causing a denial of service (CPU consumption) by performing many renegotiations within a single connection.

**Comment by nanhuirong** [comment]
> > > [https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/util/annotation/ManagedAttribute.html)("Whether](https://www.eclipse.org/jetty/javadoc/jetty-9/org/eclipse/jetty/util/annotation/ManagedAttribute.html)(%22Whether) renegotiation is allowed"
> > 
> > 
> > In our scenario，we should provide better security for the gateway. After all, the IP maybe a public IP.
> 
> What prevents you to set this new config to `false` in your environment and leave the default as `true` as intended by Jetty developers? They also introduced a limit (defaults to 5) that would fix the original CVE of causing a denial of service (CPU consumption) by performing many renegotiations within a single connection.

I got it. I don't notice the limit and update the patchset.

**Comment by lmccay** [comment]
Disabling renegotiation is the more secure mode and I would expect that to actually be the default. Renegotiation had an attack vector a while ago whereby a middle man could renegotiate to a lower - like NONE - algorithm. While this may have been fixed, I don't know of any specific functionality that is blocked by this that requires it to be enabled by default. If this was recently changed to enabled by default in jetty then we should preserve backward compatibility and leave it false. If it was enabled by default previously then making it true by default preserves previous behanvior.

**Comment by nanhuirong** [comment]
> Disabling renegotiation is the more secure mode and I would expect that to actually be the default. Renegotiation had an attack vector a while ago whereby a middle man could renegotiate to a lower - like NONE - algorithm. While this may have been fixed, I don't know of any specific functionality that is blocked by this that requires it to be enabled by default. If this was recently changed to enabled by default in jetty then we should preserve backward compatibility and leave it false. If it was enabled by default previously then making it true by default preserves previous behav

**Comment by nanhuirong** [comment]
> Disabling renegotiation is the more secure mode and I would expect that to actually be the default. Renegotiation had an attack vector a while ago whereby a middle man could renegotiate to a lower - like NONE - algorithm. While this may have been fixed, I don't know of any specific functionality that is blocked by this that requires it to be enabled by default. If this was recently changed to enabled by default in jetty then we should preserve backward compatibility and leave it false. If it was enabled by default previously then making it true by default preserves previous behavior.

The build for arm reports "no sapce". Do you have any idea for it?

**Comment by nanhuirong** [comment]
> Disabling renegotiation is the more secure mode and I would expect that to actually be the default. Renegotiation had an attack vector a while ago whereby a middle man could renegotiate to a lower - like NONE - algorithm. While this may have been fixed, I don't know of any specific functionality that is blocked by this that requires it to be enabled by default. If this was recently changed to enabled by default in jetty then we should preserve backward compatibility and leave it false. If it was enabled by default previously then making it true by default preserves previous behavior.

The default value is ture for jetty now.

**Review by smolnar82 — APPROVED** [review]
LGTM

**Review by lmccay — APPROVED** [review]
+1
LGTM

**Comment by nanhuirong** [comment]
@smolnar82 @lmccay , Can you merge the PR? This is the first PR for me.

**Comment by lmccay** [comment]
@nanhuirong - thank you for your PR and improvement!
I've merged this to master and do not think the build issue is related to this patch. If it does indeed continue and is determined to be related, we may need to revert it.

In the meantime, congrats on your first PR to Apache Knox and thanks again!

**Pull request merged**
