### PR TITLE
KNOX-2135 - Fix YARNUIV2 RM Logs sub-links

### PR DESCRIPTION
**Pull request by deepashreeraghu**
## What changes were proposed in this pull request?
The logs sublinks under the YARN's RM log links are broken. This PR includes changes in the rewrite file and service file to update the body of the logs link so that the sublinks are rewritten appropriately.

## How was this patch tested?
This patch was tested by creating a hadoop cluster and rewriting links using the knox gateway. 
The logs sublinks that were failing before patch are now working. 
Attaching a screenshot below.

 
image

In the screenshot, the link being hovered on shows the properly rewritten link in the bottom.

### CODE REVIEW

**Comment by risdenk** [comment]
@deepashreeraghu What specific version of Knox were you testing on? Is this an HDP version? The specifics matter since some of the YARN rewrite rules changed and may have already fixed this.

**Comment by deepashreeraghu** [comment]
@risdenk : Knox version is 1.0.0 and HDP version is 3.1.0
But, since most of the YARN links were failing with the rules that came with the HDP cluster, I replaced those rules with the rules defined in the master branch of this repo. With that almost all the links started working except for the RM-logs sublinks. Hence fixed it and sent here for review.

**Comment by deepashreeraghu** [comment]
Hi @risdenk, Hi @moresandeep ,
Were you able to reproduce the issue that I am pointing at ? Is the solution appropriate for the issue?
Thanks and Regards,
Deepa

**Comment by risdenk** [comment]
@deepashreeraghu sorry was US holiday this past weekend so didn't get back to this. Looking it over now.

**Comment by risdenk** [comment]
Change looks good. New rule so not much chance for regression. It is targetted to just logs.

**Comment by deepashreeraghu** [comment]
Thank you.

**Pull request merged**
