### PR TITLE
KNOX-2321 - HDFS UI rewrite rules should handle LogLevel

### PR DESCRIPTION
**Pull request by lokeshj1703**
https://issues.apache.org/jira/browse/KNOX-2321

## What changes were proposed in this pull request?

Add a rewrite rule for LogLevel in hdfs ui.

## How was this patch tested?

The patch was tested on a cluster.

### CODE REVIEW

**Comment by bharatviswa504** [comment]
This link is added to DN and explorer page also, do we need some changes for Dn and explorer  rewrite rules also to make it work?

**Comment by moresandeep** [comment]
> This link is added to DN and explorer page also, do we need some changes for Dn and explorer rewrite rules also to make it work?

We probably, should, @lokeshj1703 thoughts?

**Comment by lmccay** [comment]
Would the other UIs be addressed via global rewrite rules by any chance?

**Comment by moresandeep** [comment]
> Would the other UIs be addressed via global rewrite rules by any chance?

Global rewrite rule is a double edge sword, it might break other UIs unknowingly. I think some code duplication might be tolerable in this case.

**Comment by lmccay** [comment]
Okay - I want to cut an RC in the next day or so - so let's get this resolved.

**Comment by moresandeep** [comment]
Ah right, I'll merge this and we will followup with new JIRA if needed.

**Comment by lokeshj1703** [comment]
@bharatviswa504 @moresandeep I think it should be fine. The rewrite rules are added under section.
`<!-- outbound rewrite rules for links under utilities -->`
I think these rewrite rules apply for datanode as well as explorer html.

**Pull request merged**
